# Generated by Django 4.1.7 on 2023-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_temp', models.FloatField()),
                ('cpu_percent', models.FloatField()),
                ('mem_percent', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
